analytics: {}
color:
  brandColors:
    - '#000000'
    - '#880068'
    - '#000000'
    - '#D008A0'
    - '#D870B8'
  brandStrength: 0.709459
  lightness: 0.807432
  rhythmicContrast: 0.504504
  saturation: 0.71509
cta: {}
layout_spectrum: 0.814189
name: Global Diva Style
opengraph: {}
purpose: []
typography_spectrum: 0.412162
