analytics: {}
color:
  brandColors:
    - '#000000'
    - '#700058'
    - '#000000'
    - '#A80898'
    - '#E088D0'
  brandStrength: 0
  lightness: 0
  rhythmicContrast: 0.012387
  saturation: 0
cta: {}
layout_spectrum: 0.022522
name: Global Diva Style
opengraph: {}
purpose: []
typography_spectrum: 0.05518
