analytics: {}
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.542792
  lightness: 0.47309
  rhythmicContrast: 0.572072
  saturation: 0.819819
cta: {}
layout_spectrum: 0.15703917085193098
name: Global Diva Style
opengraph: {}
purpose: []
typography_spectrum: 0.47202912135981023
