analytics: {}
color:
  brandColors:
    - '#000000'
    - '#700058'
    - '#000000'
    - '#A80898'
    - '#E088D0'
  brandStrength: 0.990991
  lightness: 0.997747
  rhythmicContrast: 0.978603
  saturation: 0.988738
cta: {}
layout_spectrum: 0.022522
name: Global Diva Style
opengraph: {}
purpose: []
typography_spectrum: 0.05518
