analytics: {}
color:
  brandColors:
    - '#D0B0C8'
    - '#900888'
    - '#986890'
    - '#E82898'
    - '#F8B8F0'
  brandStrength: 0.709459
  lightness: 0.496621
  rhythmicContrast: 0.504503
  saturation: 0.510135
cta: {}
layout_spectrum: 0.022522
name: Global Diva Style
opengraph: {}
purpose: []
typography_spectrum: 0.05518
